### ISSUE TITLE
Consider kas

### ISSUE THREAD

**Issue by jan-kiszka** [intel/xenomai#2]
You may want to have a look at https://github.com/siemens/kas to model this in-tree, i.e. in the layer describing a complete image (could be meta-xenomai in your case). https://gitlab.denx.de/Xenomai/xenomai-images uses that pattern, though for building demo and test images from a real distribution (Debian). A Yocto example with kas can be found at https://github.com/siemens/meta-iot2000.

**Comment by finomeng** [comment]
Thanks Jan, this repo is by far design for education purpose, not for production. It only contains a fewest code to demo how to build a Linux image in Yocto/bitbake approach. We face that, most of the engineers in our community have no patience learn Yocto&bitbake; We want to find a way to make source code more straightforward to read and study, hard though.
